name = "root"
authors = ["Deltares and contributors <ribasim.info@deltares.nl>"]
description = "Meta-project used to share the Manifest of Ribasim and its dependents"

[deps]
Ribasim = "aac5e3d9-0b8f-4d4f-8241-b1a7a9632635"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
create_binaries = "3cfb6a46-05f0-43df-bb16-bf763deb14b4"
docs = "8daea9ca-fc6c-4731-aa85-717fa0b706bc"
libribasim = "f319f290-633d-4573-adfe-d6d5548b6388"
ribasim_cli = "e45c999e-e944-4589-a8e6-7d0b7a60140a"
