select = ["D", "E", "F", "NPY", "PD", "C4", "I"]
ignore = [
    "D1",
    "D202",
    "D205",
    "D206",
    "D400",
    "D404",
    "E402",
    "E501",
    "E703",
    "PD002",
    "PD901",
]
fixable = ["I"]

[pydocstyle]
convention = "numpy"
