version: '2'

services:
  qgis:
    image: qgis/qgis:release-3_30
    container_name: qgis
    volumes:
      - ../qgis/:/tests_directory/ribasim_qgis
    environment:
      - CI=true
      - DISPLAY=:99
