version: '2'

services:
  qgis:
    image: qgis/qgis:final-3_28_14
    container_name: qgis
    volumes:
      - ../ribasim_qgis/:/tests_directory/${PLUGIN_NAME}
    environment:
      - CI=true
      - DISPLAY=:99
