name: ribasim

channels:
  - conda-forge
    
dependencies:
  - black
  - geopandas
  - matplotlib
  - mypy
  - pandas
  - pandera
  - pyarrow
  - pydantic
  - pyogrio
  - python>3.9
  - pytest
  - ruff
  - shapely>=2.0
  - tomli
  - tomli-w
  - xarray
