profile:
  group:
    - [website, manual]

quartodoc:
  style: pkgdown
  dir: reference/python
  title: Python API
  package: ribasim
  options:
    include_inherited: true
    include_empty: true
    include_attributes: true
    include_classes: true
    include_functions: true
