project:
  type: website
  resources:
    - schema/*.schema.json

website:
  title: "Ribasim"
  page-navigation: true
  navbar:
    logo: https://user-images.githubusercontent.com/4471859/224825908-bee7e044-bc6b-4561-8b08-5d330cce3ed5.png
    left:
      - text: "Julia core"
        file: core/index.qmd
      - text: "Python tooling"
        file: python/index.qmd
      - text: "QGIS plugin"
        file: qgis/index.qmd
      - text: "Contributing"
        file: contribute/index.qmd
    right:
      - icon: github
        href: https://github.com/Deltares/Ribasim
        aria-label: GitHub

  sidebar:
    - title: "Julia core"
      contents:
        - core/index.qmd
        - core/modelconcept.qmd
        - core/usage.qmd
        - core/validation.qmd
        - core/equations.qmd
        - core/allocation.qmd
        - core/numerics.qmd
        - build/index.md
    - title: "Python tooling"
      contents:
        - python/index.qmd
        - python/examples.ipynb
        - python/reference/index.qmd
        - python/test-models.qmd
    - title: "Contributing"
      contents:
        - contribute/index.qmd
        - contribute/core.qmd
        - contribute/python.qmd
        - contribute/qgis.qmd
        - contribute/addnode.qmd
        - contribute/ci.qmd
        - contribute/release.qmd

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true

bibliography: references.bib
number-sections: true

quartodoc:
  style: pkgdown
  dir: python/reference
  title: API Reference
  package: ribasim
  sections:
    - title: Model
      desc: The Model class represents an entire Ribasim model.
      contents:
        - Model
    - title: Edge
      desc: The Edge database layer.
      contents:
        - EdgeTable
    - title: Node types
      desc: Available node types to model different situations.
      contents:
        - nodes.basin
        - nodes.fractional_flow
        - nodes.tabulated_rating_curve
        - nodes.pump
        - nodes.outlet
        - nodes.user_demand
        - nodes.level_boundary
        - nodes.flow_boundary
        - nodes.linear_resistance
        - nodes.manning_resistance
        - nodes.terminal
        - nodes.discrete_control
        - nodes.pid_control
        - nodes.flow_demand
        - nodes.level_demand
