project:
  type: website
  resources:
    - schema/*.schema.json

website:
  title: "Ribasim"
  page-navigation: true
  navbar:
    logo: https://user-images.githubusercontent.com/4471859/224825908-bee7e044-bc6b-4561-8b08-5d330cce3ed5.png
    left:
      - text: "Tutorials"
        file: tutorial/index.qmd
      - text: "How-to guides"
        file: guide/index.qmd
      - text: "Explanation"
        file: explanation/concept.qmd
      - text: "Reference"
        file: reference/index.qmd
      - text: "Changelog"
        file: changelog.qmd
    right:
      - icon: github
        href: https://github.com/Deltares/Ribasim
        aria-label: GitHub

  sidebar:
    - title: "Tutorials"
      contents:
        - tutorial/index.qmd
        - tutorial/qgis.qmd

    - title: "How-to guides"
      contents:
        - guide/index.qmd
        - section: "For end-users"
          contents:
          - guide/examples.ipynb
          - guide/python.qmd
          - guide/coupling.qmd
        - section: "For developers"
          contents:
          - guide/core.qmd
          - guide/qgis.qmd
          - dev/python.qmd
          - guide/addnode.qmd
          - guide/release.qmd

    - title: "Explanation"
      contents:
        - explanation/concept.qmd
        - explanation/usage.qmd
        - section: "Numerics"
          contents:
          - explanation/modelconcept.qmd
          - explanation/equations.qmd
          - explanation/numerics.qmd
        - section: "Implementation"
          contents:
          - explanation/core.qmd
          - explanation/validation.qmd
          - explanation/allocation.qmd
          - explanation/ci.qmd

    - title: "Reference"
      contents:
        - reference/index.qmd
        - reference/test-models.qmd
        - section: "Nodes"
          contents:
            - reference/node/basin.qmd
            - reference/node/tabulated-rating-curve.qmd
            - reference/node/pump.qmd
            - reference/node/outlet.qmd
            - reference/node/user-demand.qmd
            - reference/node/flow-demand.qmd
            - reference/node/level-demand.qmd
            - reference/node/flow-boundary.qmd
            - reference/node/level-boundary.qmd
            - reference/node/linear-resistance.qmd
            - reference/node/manning-resistance.qmd
            - reference/node/fractional-flow.qmd
            - reference/node/terminal.qmd
            - reference/node/discrete-control.qmd
            - reference/node/pid-control.qmd

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true

bibliography: references.bib
number-sections: true

quartodoc:
  style: pkgdown
  dir: python/reference
  title: API Reference
  package: ribasim
  sections:
    - title: Model
      desc: The Model class represents an entire Ribasim model.
      contents:
        - Model
    - title: Edge
      desc: The Edge database layer.
      contents:
        - EdgeTable
    - title: Node types
      desc: Available node types to model different situations.
      contents:
        - nodes.basin
        - nodes.fractional_flow
        - nodes.tabulated_rating_curve
        - nodes.pump
        - nodes.outlet
        - nodes.user_demand
        - nodes.level_boundary
        - nodes.flow_boundary
        - nodes.linear_resistance
        - nodes.manning_resistance
        - nodes.terminal
        - nodes.discrete_control
        - nodes.pid_control
        - nodes.flow_demand
        - nodes.level_demand
