project:
  type: website
  resources:
    - objects.json

website:
  title: "Ribasim"
  navbar:
    left:
      - equations.qmd
      - modflow.qmd
      - coupling-demo.qmd
      - developer.qmd
      - python/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

bibliography: references.bib
number-sections: true

quartodoc:
  style: pkgdown
  dir: python/reference
  title: API Reference
  package: ribasim
  sections:
    - title: Model
      desc: The Model class represents an entire Ribasim model.
      contents:
        - Model
    - title: Network
      desc: The Node and Edge GeoPackage layers define the network layout.
      contents:
        - Node
        - Edge
    - title: Node types
      desc: Available node types to model different situations.
      contents:
        - Basin
        - TabulatedRatingCurve
        - LinearLevelConnection
        - FractionalFlow
        - LevelControl
    - title: Utility functions
      desc: Collection of utility functions.
      contents:
        - utils.geometry_from_connectivity
        - utils.connectivity_from_geometry
