project:
  type: website
  resources:
    - schema/*.schema.json

website:
  title: "Ribasim"
  page-navigation: true
  navbar:
    logo: https://user-images.githubusercontent.com/4471859/224825908-bee7e044-bc6b-4561-8b08-5d330cce3ed5.png
    left:
      - text: "About"
        file: index.qmd
      - text: "Get Started"
        file: tutorials/index.qmd
      - text: "Guides"
        file: guides/index.qmd
      - text: "Background"
        file: background/concept.qmd
      - text: "Reference"
        file: reference/index.qmd
      - text: "Changelog"
        file: changelog.md
    right:
      - icon: github
        href: https://github.com/Deltares/Ribasim
        aria-label: GitHub

  sidebar:
    - title: "Get Started"
      contents:
        - tutorials/index.qmd
        - tutorials/julia.qmd
        - tutorials/python.qmd
        - tutorials/qgis.qmd

    - title: "Guides"
      contents:
        - guides/index.qmd
        - section: "For end-users"
          contents:
          - guides/examples.ipynb
          - guides/python.qmd
          - guides/coupling.qmd
        - section: "For developers"
          contents:
          - guides/core.qmd
          - guides/qgis.qmd
          - dev/python.qmd
          - guides/addnode.qmd
          - guides/release.qmd
          - guides/bmi.qmd

    - title: "Background"
      contents:
        - background/concept.qmd
        - background/usage.qmd
        - section: "Numerics"
          contents:
          - background/modelconcept.qmd
          - background/equations.qmd
          - background/numerics.qmd
        - section: "Implementation"
          contents:
          - background/core.qmd
          - background/validation.qmd
          - background/allocation.qmd
          - background/ci.qmd

    - title: "Reference"
      contents:
        - reference/index.qmd
        - reference/test-models.qmd
        - section: "Nodes"
          contents:
            - reference/node/basin.qmd
            - reference/node/tabulated-rating-curve.qmd
            - reference/node/pump.qmd
            - reference/node/outlet.qmd
            - reference/node/user-demand.qmd
            - reference/node/flow-demand.qmd
            - reference/node/level-demand.qmd
            - reference/node/flow-boundary.qmd
            - reference/node/level-boundary.qmd
            - reference/node/linear-resistance.qmd
            - reference/node/manning-resistance.qmd
            - reference/node/fractional-flow.qmd
            - reference/node/terminal.qmd
            - reference/node/discrete-control.qmd
            - reference/node/pid-control.qmd

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true

bibliography: references.bib
number-sections: true

quartodoc:
  style: pkgdown
  dir: python/reference
  title: API Reference
  package: ribasim
  sections:
    - title: Model
      desc: The Model class represents an entire Ribasim model.
      contents:
        - Model
    - title: Edge
      desc: The Edge database layer.
      contents:
        - EdgeTable
    - title: Node types
      desc: Available node types to model different situations.
      contents:
        - nodes.basin
        - nodes.fractional_flow
        - nodes.tabulated_rating_curve
        - nodes.pump
        - nodes.outlet
        - nodes.user_demand
        - nodes.level_boundary
        - nodes.flow_boundary
        - nodes.linear_resistance
        - nodes.manning_resistance
        - nodes.terminal
        - nodes.discrete_control
        - nodes.pid_control
        - nodes.flow_demand
        - nodes.level_demand
