name = "docs"
uuid = "8daea9ca-fc6c-4731-aa85-717fa0b706bc"
authors = ["Deltares and contributors <ribasim.info@deltares.nl>"]
description = "Build Ribasim docs and generate schemas"
manifest = "../Manifest.toml"
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterMarkdown = "997ab1e6-3595-5248-9280-8efb232c3433"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Ribasim = "aac5e3d9-0b8f-4d4f-8241-b1a7a9632635"

[compat]
Documenter = "0.27"
DocumenterMarkdown = "0.2"
InteractiveUtils = "1"
JSON3 = "1.12"
OrderedCollections = "1.6"
julia = "1.9"
