name: Julia Tests
on:
  push:
    branches: [main]
    paths-ignore: [".teamcity/**"]
    tags: ["*"]
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Julia ${{ matrix.julia_version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia_version:
          - "~1.10.0-0"
        os:
          - ubuntu-latest
          # https://github.com/Deltares/Ribasim/issues/825
          # - macOS-latest
          - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.4.1
        with:
          pixi-version: "latest"
      - name: Prepare pixi
        run: pixi run install-without-pre-commit
      - name: Prepare model input
        run: |
          pixi run generate-testmodels
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia_version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
        with:
          cache-compiled: "true"
          cache-registries: "true"
      - uses: julia-actions/julia-buildpkg@v1
        with:
          project: core
      - uses: julia-actions/julia-runtest@v1
        with:
          project: core
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: core/src
      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info
