name: Julia Tests
on:
  push:
    branches: [main]
    tags: ["*"]
    paths: [".github/**", "build/libribasim/src/**", "core/**"]
  pull_request:
    paths: [".github/**", "build/libribasim/src/**", "core/**"]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Julia ${{ matrix.julia_version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        julia_version:
          - "1.8"
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
        include:
          - os: ubuntu-latest
            version: "~1.9.0-0"
            arch: x64
    steps:
      - uses: actions/checkout@v3
      - name: Setup Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          python_version: "3.11"
          cache-downloads: true
          cache-env: true
          environment-file: ./environment.yml
      - name: Install ribasim
        run: pip install --editable python/ribasim
      - name: Prepare model input
        run: python python/ribasim/tests/conftest.py
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia_version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
        with:
          project: core
      - uses: julia-actions/julia-runtest@v1
        with:
          project: core
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: core/src
      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info
