name: Julia Tests
on:
  push:
    branches: [main]
    paths-ignore: [".teamcity/**"]
    tags: ["*"]
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Julia ${{ matrix.julia_version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        julia_version:
          - "1.9"
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-downloads: true
          cache-environment: true
          environment-file: ./environment.yml
      - name: Install ribasim
        run: pip install --editable python/ribasim
      - name: Install ribasim_testmodels
        run: pip install --editable python/ribasim_testmodels
      - name: Prepare model input
        run: python python/ribasim/tests/conftest.py
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia_version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
        with:
          cache-compiled: "true"
          cache-registries: "true"
      - uses: julia-actions/julia-buildpkg@v1
        with:
          project: core
      - uses: julia-actions/julia-runtest@v1
        with:
          project: core
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: core/src
      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info
