name: Julia Tests
on:
  push:
    branches: [main]
    paths-ignore: [".teamcity/**"]
    tags: ["*"]
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read
jobs:
  test:
    name: Julia ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # https://github.com/Deltares/Ribasim/issues/825
          # - macOS-latest
          - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/cache@v1
        with:
          cache-compiled: "true"
          cache-registries: "true"
      - uses: prefix-dev/setup-pixi@v0.4.3
        with:
          pixi-version: "latest"
      - name: Prepare pixi
        run: pixi run install-without-pre-commit
      - name: Test Ribasim Core
        run: |
          pixi run test-ribasim-core-cov
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: core/src
      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info
