name: Docs
on:
  push:
    branches: [main]
    paths-ignore: [".teamcity/**"]
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  publish:
    name: Docs Julia ${{ matrix.julia_version }} - ${{ matrix.arch }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        julia_version:
          - "~1.10.0-0"
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia_version }}
          arch: ${{ matrix.arch }}

      - uses: julia-actions/julia-buildpkg@v1
        with:
          project: core

      - uses: julia-actions/cache@v1
        with:
          cache-compiled: "true"
          cache-registries: "true"

      - uses: prefix-dev/setup-pixi@v0.4.0
        with:
          pixi-version: "latest"
      - name: Prepare pixi
        run: pixi run install-without-pre-commit

      - name: Check Quarto installation and all engines
        run: pixi run quarto-check

      - name: Generate Julia docs
        run: pixi run build-julia-docs

      - name: Render Quarto Project
        run: pixi run quarto-render

      - name: Publish Quarto Project
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
