name: Pre-commit

on:
  schedule:
  # every monday morning
    - cron: "0 7 * * MON"
  # on demand
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: browniebroke/pre-commit-autoupdate-action@main
      - uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "Update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
          author: "GitHub <noreply@github.com>"
