name: Ribasim Python Tests
on:
  push:
    branches: [main]
    tags: ["*"]
    paths: [".github/**", "python/ribasim/**"]
  pull_request:
    paths: [".github/**", "python/ribasim/**"]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Ribasim Python ${{ matrix.python_version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        python_version:
          - "3.9"
          - "3.10"
          - "3.11"
        arch:
          - x64
    steps:
      - uses: actions/checkout@v3

      - name: Setup Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          python_version: ${{ matrix.python_version }}
          cache-downloads: true
          cache-env: true
          environment-file: ./environment.yml

      - name: Install ribasim
        run: pip install -e python/ribasim

      - name: Run tests
        run: pytest python/ribasim/tests
