name: Python Codegen
on:
  push:
    branches: [main, update/pixi-lock]
    paths-ignore: [".teamcity/**"]
    tags: ["*"]
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  codegen:
    name: Codegen
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.7.0
        with:
          pixi-version: "latest"
      - name: Test if codegen runs without errors
        run: pixi run codegen
      - name: Ensure that no code has been generated
        run: git diff --exit-code
