name: Python Lint
on:
  push:
    branches: [main]
    paths-ignore: [".teamcity/**"]
    tags: ["*"]
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  mypy:
    name: Mypy
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.4.1
        with:
          pixi-version: v0.7.0
      - name: Prepare pixi
        run: pixi run install-without-pre-commit
      - name: Run mypy on python/ribasim
        run: |
          pixi run mypy-ribasim-python
      - name: Run mypy on python/ribasim_testmodels
        run: |
          pixi run mypy-ribasim-testmodels
      - name: Run mypy on python/ribasim_api
        run: |
          pixi run mypy-ribasim-api
