name: Python Lint
on:
  push:
    branches: [main]
    tags: ["*"]
    paths: [".github/**", "python/**"]
  pull_request:
    paths: [".github/**", "python/**"]
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  mypy:
    name: Mypy
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-downloads: true
          cache-environment: true
          environment-file: ./environment.yml
      - name: Install python packages
        run: |
          pip install python/ribasim
          pip install python/ribasim_testmodels
          pip install python/ribasim_api
      - name: Run mypy on python/ribasim
        run: |
          mypy --ignore-missing-imports python/ribasim/ribasim
      - name: Run mypy on python/ribasim_testmodels
        run: |
          mypy --ignore-missing-imports python/ribasim_testmodels/ribasim_testmodels
      - name: Run mypy on python/ribasim_api
        run: |
          mypy --ignore-missing-imports python/ribasim_api/ribasim_api
