name: Ribasim Python Tests
on:
  push:
    branches: [main]
    tags: ["*"]
    paths: [".github/**", "python/ribasim/**"]
  pull_request:
    paths: [".github/**", "python/ribasim/**"]
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Python ${{ matrix.python_version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        python_version:
          - "3.9"
          - "3.10"
          - "3.11"
        arch:
          - x86
    steps:
      - uses: actions/checkout@v3

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-downloads: true
          cache-environment: true
          environment-file: ./environment.yml
          create-args: >-
            python=${{ matrix.python_version }}

      - name: Install ribasim
        run: pip install --editable python/ribasim

      - name: Install ribasim_testmodels
        run: pip install --editable python/ribasim_testmodels

      - name: Run tests
        run: pytest --cov=ribasim --cov-report=xml python/ribasim/tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
