name: Ribasim Python Tests
on:
  push:
    branches: [main]
    paths-ignore: [".teamcity/**"]
    tags: ["*"]
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Python ${{ matrix.python_version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        python_version:
          - "3.9"
          - "3.10"
          - "3.11"
        arch:
          - x86
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.2.0
        with:
          pixi-version: latest
          cache: true
      - name: Prepare pixi
        run: |
          pixi install
          pixi run post-install

      - name: Run tests
        run: pixi run test-ribasim-python-cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
