name: Python Lint
on:
  push:
    branches: [main]
    tags: ["*"]
    paths: [".github/**", "python/**"]
  pull_request:
    paths: [".github/**", "python/**"]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  black:
    name: Python ${{ matrix.python_version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        arch:
          - x64
        python_version:
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          python_version: ${{ matrix.python_version }}
          cache-downloads: true
          cache-env: true
          environment-file: ./environment.yml
      - name: Run black
        run: |
          black --check python

  ruff:
    name: Python ${{ matrix.python_version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        arch:
          - x64
        python_version:
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          python_version: ${{ matrix.python_version }}
          cache-downloads: true
          cache-env: true
          environment-file: ./environment.yml
      - name: Run ruff
        run: |
          ruff check --format=github python


  mypy:
    name: Python ${{ matrix.python_version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        arch:
          - x64
        python_version:
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          python_version: ${{ matrix.python_version }}
          cache-downloads: true
          cache-env: true
          environment-file: ./environment.yml
      - name: Run mypy
        run: |
          mypy --ignore-missing-imports python/ribasim