name: Python Tests
on:
  push:
    branches: [main]
    tags: ["*"]
    paths: [".github", "python"]
  pull_request:
jobs:
  test:
    name: Python Tests ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
        arch:
          - x64
    steps:
      - uses: actions/checkout@v3

      - name: Setup Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          python-version: ${{ matrix.python-version }}
          cache-downloads: true
          cache-env: true
          environment-file: ./python/environment.yml

      - name: Install ribasim
        working-directory: python
        run: pip install -e .

      - name: Run tests
        working-directory: python
        run: pytest tests
