name: QGIS Tests

on:
    push:
      branches: [main]
      paths-ignore: [".teamcity/**"]
      tags: ["*"]
    pull_request:
    merge_group:
jobs:
    test-qgis:
        name: "Test"
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: .docker
        steps:

        - name: Check out repository
          uses: actions/checkout@v4
        - name: Launching docker compose
          run: ./start.sh
        - name: Running tests
          run: ./test.sh
        - name: Stopping docker compose
          run: ./stop.sh
